openapi: 3.0.0
info:
  title: API Documentation
  version: 1.0.0
  description: API documentation for the application.
servers:
  # - url: http://localhost:3000/api/v2
  #   description: Local server

  - url: https://stormy-hamlet-97616-f066246815d5.herokuapp.com/api/v2
    description: Heroku Server

paths:
#member
  /members:
    $ref: 'members.yaml#/paths/~1members'
  /member:
    $ref: 'members.yaml#/paths/~1member'
  /member/signUp:
    $ref: 'members.yaml#/paths/~1member~1signUp'
  /member/login:
    $ref: 'members.yaml#/paths/~1member~1login'
  /member/{member_id}:
    $ref: 'members.yaml#/paths/~1member~1{member_id}'
#judge
  /judges/event/{event_id}:
    $ref: 'judges.yaml#/paths/~1judges~1event~1{event_id}'

  /transaction:
    $ref: 'judges.yaml#/paths/~1transaction'

  /{id}/transaction:
    $ref: 'judges.yaml#/paths/~1{id}~1transaction'
  
  /score:
    $ref: 'judges.yaml#/paths/~1score'

  /events/judge/{judge_id}:
    $ref: 'judges.yaml#paths/~1events~1judge~1{judge_id}'

#organizers
  /event:
    $ref: 'organizers.yaml#/paths/~1event'
  /event/scoreMatrix:
    $ref: 'organizers.yaml#/paths/~1event~1scoreMatrix'
  /event/investMatrix:
    $ref: 'organizers.yaml#/paths/~1event~1investMatrix'
  /event/judges:
    $ref: 'organizers.yaml#/paths/~1event~1judges'
  /event/editors:
    $ref: 'organizers.yaml#/paths/~1event~1editors'
  /event/team:
    $ref: 'organizers.yaml#/paths/~1event~1team'
  /event/teams:
    $ref: 'organizers.yaml#/paths/~1event~1teams'
  /event/scoreTypes:
    $ref: 'organizers.yaml#/paths/~1event~1scoreTypes'
  
#events
  /events:
    $ref: 'events.yaml#/paths/~1events'
  /events/judge/{judge_id}:
    $ref: 'events.yaml#/paths/~1events~1judge~1{judge_id}'
  /event/{id}:
    $ref: 'events.yaml#/paths/~1event~1{id}'
  /scoreCategory/event/{event_id}:
    $ref: 'events.yaml#/paths/~1scoreCategory~1event~1{event_id}'

#teams
  /teams/event/{event_id}:
    $ref: 'teams.yaml#/paths/~1teams~1event~1{event_id}'
  /teams/event/{event_id}/totalScore:
    $ref: 'teams.yaml#/paths/~1teams~1event~1{event_id}~1totalScore'
  /team/event/{event_id}/judge/{judge_id}:
    $ref: 'teams.yaml#/paths/~1team~1event~1{event_id}~1judge~1{judge_id}'

#teamLeaders
  /team:
    $ref: 'teamLeaders.yaml#/paths/~1team'
#teamMembers
  /team/member:
    $ref: 'teamMembers.yaml#/paths/~1team~1member'
  /team/{team_id}/member/{member_id}:
    $ref: 'teamMembers.yaml#/paths/~1team~1{team_id}~1member~1{member_id}'
#transcationLog
  /transaction/event/{event_id}:
    $ref: 'transactionLog.yaml#/paths/~1transaction~1event~1{event_id}'
  /transaction/event/{event_id}/judge/{judge_id}:
    $ref: 'transactionLog.yaml#/paths/~1transaction~1event~1{event_id}~1judge~1{judge_id}'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
   
    
security:
  - bearerAuth: []
