openapi: 3.0.0
info:
  title: Teams API
  version: 1.0.0

paths:
  /teams/event/{event_id}:
    get:
      tags:
        - Teams
      summary: Get all teams by event ID
      operationId: getTeamsByEventId
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTeamsByEventIdResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Teams not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /teams/event/{event_id}/totalScore:
    get:
      tags:
        - Teams
      summary: Get total scores of all teams by event ID
      operationId: getTeamsTotalScoreByEventId
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTeamsTotalScoreByEventIdResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Teams not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /team/event/{event_id}/judge/{judge_id}:
    get:
      tags:
        - Teams
      summary: Get amount invested by each judge in an event
      operationId: getTeamsAmountInvestedByJudge
      parameters:
        - name: event_id
          in: path
          required: true
          schema:
            type: integer
        - name: judge_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetTeamsAmountInvestedByJudgeResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Data not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    GetTeamsByEventIdResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          properties:
            teams:
              type: array
              items:
                $ref: '#/components/schemas/Team'
      example:
        success: true
        message:
          teams:
            - id: 104
              name: "SoyaByte"
              desc: "soyaByte"
              active: true
              website_link: "link"
              organizer_id: 6
              created_at: "2024-03-20T12:09:29.403Z"
              updated_at: "2024-03-20T12:09:29.403Z"
              event_id: 38
              total_score: 0.0
              pitching_order: 1
            - id: 91
              name: "Bakefia"
              desc: "Bakefia"
              active: true
              website_link: "link"
              organizer_id: 6
              created_at: "2024-03-20T12:01:51.833Z"
              updated_at: "2024-03-20T12:01:51.833Z"
              event_id: 38
              total_score: 0.0
              pitching_order: 10
            - id: 93
              name: "CareChic"
              desc: "CareChic"
              active: true
              website_link: "link"
              organizer_id: 6
              created_at: "2024-03-20T12:03:02.490Z"
              updated_at: "2024-03-20T12:03:02.490Z"
              event_id: 38
              total_score: 0.0
              pitching_order: 13
    GetTeamsTotalScoreByEventIdResponse:
      type: array
      items:
         GetTeamsTotalScoreByEventIdResponse:
      type: array
      items:
        $ref: '#/components/schemas/TeamWithTotalScore'
    GetTeamsAmountInvestedByJudgeResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: object
          properties:
            judge:
              $ref: '#/components/schemas/Judge'
      example:
        success: true
        message:
          judge:
            id: 139
            member_id: 151
            event_id: 38
            current_amount: 0
            created_at: "2024-03-21T09:17:58.651Z"
            updated_at: "2024-03-22T09:18:49.487Z"
            active: true
            judge_type: "judge"

    TeamWithTotalScore:
          type: object
          properties:
            id:
              type: integer
            event_id:
              type: integer
            active:
              type: boolean
            desc:
              type: string
              nullable: true
            name:
              type: string
            pitching_order:
              type: integer
              nullable: true
            website_link:
              type: string
              nullable: true
            teamEvents:
              type: array
              items:
                $ref: '#/components/schemas/TeamEvent'
    Team:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        desc:
          type: string
          nullable: true
        active:
          type: boolean
        website_link:
          type: string
          nullable: true
        organizer_id:
          type: integer
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        event_id:
          type: integer
        total_score:
          type: number
          format: float
          nullable: true
        pitching_order:
          type: integer
          nullable: true
        TeamWithTotalScore:
      type: object
      properties:
        id:
          type: integer
        event_id:
          type: integer
        active:
          type: boolean
        desc:
          type: string
          nullable: true
        name:
          type: string
        pitching_order:
          type: integer
          nullable: true
        website_link:
          type: string
          nullable: true
        teamEvents:
          type: array
          items:
            $ref: '#/components/schemas/TeamEvent'
    TeamEvent:
      type: object
      properties:
        id:
          type: integer
        team_id:
          type: integer
        event_id:
          type: integer
        total_score:
          type: number
          format: float
    Judge:
      type: object
      properties:
        id:
          type: integer
        member_id:
          type: integer
        event_id:
          type: integer
        current_amount:
          type: number
          format: float
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        active:
          type: boolean
        judge_type:
          type: string

    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        errors:
          type: array
          items:
            type: string