default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: root
  host: localhost

development:
  <<: *default
  database: leader_board_db

test:
  <<: *default
  database: leader_board_db
production: <%= ENV['DATABASE_URL'] %>
